#!/usr/bin/env bash
# gen-event-type-enum.sh - projects metrics/taxonomy/event-types.yaml into
# schemas/records/event-type.enum.json. The enum is GENERATED, never hand-edited.
# Master Spec v4.0 Section 97.3 line 8959.
set -eu
CP_ROOT="${CP_ROOT:?CP_ROOT must be set}"
L4_PY="${L4_PY:?L4_PY must be set}"
"$L4_PY" - "$CP_ROOT/metrics/taxonomy/event-types.yaml" "$CP_ROOT/schemas/records/event-type.enum.json" <<'PY'
import json
import sys

import yaml

src, dst = sys.argv[1], sys.argv[2]
doc = yaml.safe_load(open(src, encoding="utf-8"))
rows = doc["event_types"]
ids = [r["id"] for r in rows]
if len(set(ids)) != len(ids):
    print("GEN FAIL: duplicate identifier in taxonomy")
    sys.exit(1)
out = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "event-type.enum.json",
    "title": "Closed event_type enum",
    "description": (
        "GENERATED by tools/records/gen-event-type-enum.sh from "
        "metrics/taxonomy/event-types.yaml. Do not hand-edit. "
        "Master Spec v4.0 Section 97.3 line 8959."
    ),
    "type": "string",
    "enum": ids,
}
open(dst, "w", encoding="utf-8", newline="\n").write(json.dumps(out, indent=2) + "\n")
print("GENERATED %d" % len(ids))
PY
