#!/usr/bin/env bash
# ops-vm/layer-b/allowlist/sync-allowlist.sh
# Section 99.5: "capability-derived Grafana access uses GitHub OAuth into
# Grafana plus a sync job from the registries. No separate IdP."
# Section 90.4: access derives from the capability "and from nothing else".
#
# Usage: sync-allowlist.sh [--dry-run] [--holders-file <path>]
# With no --holders-file the artifact path is read from the frozen contract
# at contracts/access/access-inputs.yaml : layer_b.capability_holders_artifact.
# This script contains no login. If you are about to add one, stop.
set -euo pipefail
DRY=0; HOLDERS_FILE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY=1; shift ;;
    --holders-file) HOLDERS_FILE="${2:?path}"; shift 2 ;;
    *) echo "UNKNOWN_ARG $1"; exit 2 ;;
  esac
done
CONTRACT="contracts/access/access-inputs.yaml"
if [ -z "$HOLDERS_FILE" ]; then
  if [ ! -f "$CONTRACT" ]; then
    echo "CONTRACT_MISSING $CONTRACT (L0 Phase-0 frozen input not yet published)"
    exit 2
  fi
  HOLDERS_FILE=$(yq -r '.layer_b.capability_holders_artifact // ""' "$CONTRACT")
fi
[ -n "$HOLDERS_FILE" ] || { echo "HOLDERS_ARTIFACT_MISSING (layer_b.capability_holders_artifact is unset in $CONTRACT)"; exit 2; }
[ -f "$HOLDERS_FILE" ] || { echo "HOLDERS_ARTIFACT_UNREADABLE $HOLDERS_FILE"; exit 2; }

# The holders of people-intelligence, and nothing else. Sorted, deduplicated.
WANT=$(yq -r '.capabilities["people-intelligence"].holders[]' "$HOLDERS_FILE" | sort -u)
[ -n "$WANT" ] || { echo "NO_HOLDERS_IN_ARTIFACT"; exit 2; }

API="http://127.0.0.1:3001"
HAVE=$(ssh layerb-host "curl -s -u \"\$LAYERB_ADMIN\" $API/api/org/users | jq -r '.[].login'" 2>/dev/null | sort -u || true)

ADD=$(comm -23 <(printf '%s\n' "$WANT") <(printf '%s\n' "$HAVE"))
DEL=$(comm -13 <(printf '%s\n' "$WANT") <(printf '%s\n' "$HAVE"))

if [ "$DRY" -eq 1 ]; then
  echo "SYNC_PLAN add=$(printf '%s\n' "$ADD" | grep -c . ) remove=$(printf '%s\n' "$DEL" | grep -c . )"
  exit 0
fi

for login in $ADD; do
  pw=$(openssl rand -hex 24)   # generated on the host, unused: login is OAuth only
  ssh layerb-host "curl -s -u \"\$LAYERB_ADMIN\" -X POST $API/api/admin/users \
    -H 'Content-Type: application/json' \
    -d '{\"name\":\"$login\",\"login\":\"$login\",\"password\":\"$pw\"}' >/dev/null"
  echo "ADDED $login"
done

for login in $DEL; do
  # layerb-admin is the instance's own built-in admin and is never present in
  # the people-intelligence holder list. Without this guard the first
  # non-dry-run deletes it and locks the Founder out irreversibly.
  [ "$login" = "layerb-admin" ] && continue
  id=$(ssh layerb-host "curl -s -u \"\$LAYERB_ADMIN\" $API/api/users/lookup?loginOrEmail=$login | jq -r '.id'")
  ssh layerb-host "curl -s -u \"\$LAYERB_ADMIN\" -X DELETE $API/api/admin/users/$id >/dev/null"
  echo "REMOVED $login"
done

# Directory-per-item record of the holder set (PARTITION.md rule 3).
OUT="ops-vm/layer-b/allowlist/holders"
mkdir -p "$OUT"
find "$OUT" -name '*.yaml' -delete
for login in $WANT; do
  printf 'login: "%s"\nderived_from: "people-intelligence capability"\nsynced_at: "%s"\n' \
    "$login" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$OUT/$login.yaml"
done

# The backup-store read list derives from the same holders (Section 51.4).
python3 - "$HOLDERS_FILE" <<'PY'
import sys, subprocess, datetime
holders = subprocess.run(
    ["yq", "-r", '.capabilities["people-intelligence"].holders[]', sys.argv[1]],
    capture_output=True, text=True, check=True).stdout.split()
path = "infra/layer-b/backup-read-access-list.yaml"
body = [
    "# infra/layer-b/backup-read-access-list.yaml",
    "# Generated by ops-vm/layer-b/allowlist/sync-allowlist.sh. Never hand-edited.",
    'read_access:',
    '  derived_from: "holders of the people-intelligence capability (Section 90.4)"',
    "  entries:",
]
if holders:
    body += ['    - "%s"' % h for h in sorted(set(holders))]
else:
    body[-1] = "  entries: []"
body += ['reviewed_with: "Section 49 asset inventory sweep"',
         'synced_at: "%sZ"' % datetime.datetime.utcnow().replace(microsecond=0).isoformat(), ""]
open(path, "w", encoding="utf-8").write("\n".join(body))
PY

echo "SYNC_OK holders=$(printf '%s\n' "$WANT" | grep -c .)"
