#!/usr/bin/env python
"""Generate a product repository's CODEOWNERS from a registry-derived input.

Spec Section 11.3:
  "CODEOWNERS routes review requests automatically and is generated from the
   registries rather than hand-maintained; the generator emits human identities
   only. verification/ is owned by whoever holds verification_responsibility.
   product.yaml, migration directories and CI workflow files are owned by the
   Team Lead role. Product source paths are owned by the product Team."

Human identities only (D53). If any identity in the input is not a human, the
generator REFUSES TO EMIT ANYTHING and exits 2. It never drops the offending
entry and emits the rest: a silently pruned routing table is worse than no file.

Pattern syntax in the denylist is deliberately NOT fnmatch. Only "*" is a
wildcard; every other character, square brackets included, is literal. Under
fnmatch the pattern "*[bot]" is a character class matching any login ending in
b, o or t -- which refuses "product-example-product" and every other ordinary
slug. Here it means "ends with the literal text [bot]", which is what the
denylist says.

Usage:
  generate_codeowners.py --org ORG_LOGIN --input INPUT.json
Exit codes:
  0  CODEOWNERS written to stdout
  2  a machine identity was present -- refused (message on stderr)
  3  the input document is missing, unreadable or the wrong shape
"""
import argparse
import json
import os
import re
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
DENYLIST = os.path.join(ROOT, "access", "codeowners", "machine-identity-denylist.yaml")

REQUIRED_KEYS = ("product_id", "product_team_slug", "team_lead_team_slug",
                 "verification_responsibility", "migration_paths", "source_paths")


def refuse(reason):
    sys.stderr.write("CODEOWNERS-REFUSED %s\n" % reason)
    sys.exit(2)


def bad_input(reason):
    sys.stderr.write("CODEOWNERS-INPUT-ERROR %s\n" % reason)
    sys.exit(3)


def load_denylist(path):
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def pattern_to_regex(pattern):
    """Only '*' is a wildcard. Every other character is literal.

    Square brackets are literal here. fnmatch would read "[bot]" as a character
    class matching b, o or t, so "*[bot]" would refuse every login ending in one
    of those letters -- "product-example-product" among them.
    """
    parts = [re.escape(part) for part in pattern.split("*")]
    return re.compile("^" + ".*".join(parts) + "$")


def check_login(login, deny):
    lowered = login.lower()
    for pattern in deny["login_patterns_refused"]:
        if pattern_to_regex(pattern.lower()).match(lowered):
            return "login %r matches refused machine pattern %r" % (login, pattern)
    for named in deny["named_machine_credentials_refused"]:
        if lowered == named.lower():
            return "login %r is the named fifth-tier machine credential %r" % (login, named)
    return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--org", required=False)
    parser.add_argument("--input", required=False)
    args = parser.parse_args()

    if not args.org:
        bad_input("--org is required; the organisation login is never committed")
    if not args.input:
        bad_input("--input is required")
    if not os.path.exists(args.input):
        bad_input("input document not found: %s" % args.input)

    deny = load_denylist(DENYLIST)

    try:
        with open(args.input, "r", encoding="utf-8") as handle:
            doc = json.load(handle)
    except ValueError as exc:
        bad_input("input document is not valid JSON: %s" % exc)

    for key in REQUIRED_KEYS:
        if key not in doc:
            bad_input("input document is missing required key %r" % key)

    verification = doc["verification_responsibility"]
    if verification.get("kind") not in deny["identity_kinds_admitted"]:
        refuse("verification_responsibility kind %r is not human"
               % verification.get("kind"))
    problem = check_login(str(verification.get("login", "")), deny)
    if problem:
        refuse(problem)

    for slug_key in ("product_team_slug", "team_lead_team_slug"):
        problem = check_login(str(doc[slug_key]), deny)
        if problem:
            refuse("%s: %s" % (slug_key, problem))

    org = args.org
    product_team = "@%s/%s" % (org, doc["product_team_slug"])
    lead_team = "@%s/%s" % (org, doc["team_lead_team_slug"])
    verifier = "@%s" % verification["login"]

    lines = [
        "# GENERATED FILE - DO NOT EDIT BY HAND.",
        "# Generated by access/codeowners/generate_codeowners.py from a",
        "# registry-derived input document. Spec Section 11.3.",
        "# Human identities only: no machine account ever appears here, so a",
        "# machine-account approval can never satisfy branch protection (D53).",
        "# Product: %s" % doc["product_id"],
        "",
        "%-40s %s" % ("*", product_team),
    ]
    for path in doc["source_paths"]:
        lines.append("%-40s %s" % ("/" + path.lstrip("/"), product_team))
    lines.append("%-40s %s" % ("/verification/", verifier))
    lines.append("%-40s %s" % ("/product.yaml", lead_team))
    for path in doc["migration_paths"]:
        lines.append("%-40s %s" % ("/" + path.lstrip("/"), lead_team))
    lines.append("%-40s %s" % ("/.github/workflows/", lead_team))

    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
