#!/usr/bin/env bash
# sync-records.sh — L3 record synchronization (L3-01, FD-087)
# Usage: bash scripts/l3/sync-records.sh [--source people|board|work|all] [--mode dry|apply]
#
#   people  copies registries/people/*.yaml -> records/people/ (real source, always available)
#   work    copies registries/work/*.yaml -> records/work/open.yaml when registries/work/
#           exists; otherwise writes an honest bootstrap-empty snapshot, because no
#           work-item registry exists yet
#   board   derives records/board/snapshot.yaml columns from records/work/open.yaml.
#           _meta.status is "synced" only when real work items were found there, and
#           "bootstrap-empty" otherwise — it is never stamped "synced" against
#           fabricated/static data
#   all     runs people, then work, then board (board is run last so it reflects
#           whatever work sync just produced)
set -euo pipefail
shopt -s nullglob

SOURCE="all"
MODE="dry"

while [[ $# -gt 0 ]]; do
  case $1 in
    --source) SOURCE="$2"; shift 2;;
    --mode) MODE="$2"; shift 2;;
    *)
      echo "Unknown flag: $1" >&2
      echo "Usage: bash scripts/l3/sync-records.sh [--source people|board|work|all] [--mode dry|apply]" >&2
      exit 2
      ;;
  esac
done

echo "=== L3 Record Sync: source=$SOURCE mode=$MODE ==="

sync_people() {
  echo "Syncing registries/people/ -> records/people/"
  if [[ "$MODE" == "apply" ]]; then
    mkdir -p records/people
    SYNCED_COUNT=0
    for PERSON_FILE in registries/people/*.yaml; do
      [[ -f "$PERSON_FILE" ]] || continue
      PERSON_ID=$(basename "$PERSON_FILE" .yaml)
      [[ "$PERSON_ID" == "_canary" ]] && continue
      # Derive L3 view of person (simplified for records)
      cp "$PERSON_FILE" "records/people/${PERSON_ID}.yaml"
      echo "  Synced: $PERSON_ID"
      SYNCED_COUNT=$((SYNCED_COUNT + 1))
    done
    if [[ "$SYNCED_COUNT" -eq 0 ]]; then
      echo "  ERROR: no person files were synced from registries/people/ (directory empty, missing, or only contained _canary)" >&2
      exit 1
    fi
  else
    echo "  [DRY-RUN] Would sync people registry to records/people/"
  fi
}

sync_work() {
  echo "Syncing registries/work/ -> records/work/open.yaml"
  if [[ "$MODE" == "apply" ]]; then
    mkdir -p records/work
    NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    if [[ -d registries/work ]]; then
      # A real work-item registry exists — genuinely sync it.
      python3 - "$NOW" <<'PYEOF'
import glob
import os
import sys

import yaml

now = sys.argv[1]
items = []
for path in sorted(glob.glob("registries/work/*.yaml")):
    name = os.path.basename(path)
    if name.startswith("_"):
        continue
    with open(path) as f:
        data = yaml.safe_load(f) or {}
    data.setdefault("id", os.path.splitext(name)[0])
    items.append(data)

status = "synced" if items else "bootstrap-empty"
doc = {
    "_meta": {
        "generated": now,
        "schema": "urn:multiproduct:schemas:work:open:v1",
        "status": status,
    },
    "items": items,
}
header = "# Open work items snapshot — generated by sync-records.sh at {}\n".format(now)
with open("records/work/open.yaml", "w") as f:
    f.write(header)
    yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False)

print("  Synced: {} item(s) from registries/work/ (status={})".format(len(items), status))
PYEOF
    else
      # No work-item registry exists yet under registries/work/ — write an
      # honest bootstrap-empty snapshot rather than fabricating items.
      cat > records/work/open.yaml <<EOF
# Open work items snapshot — generated by sync-records.sh at $NOW
_meta:
  generated: "$NOW"
  schema: "urn:multiproduct:schemas:work:open:v1"
  status: "bootstrap-empty"
items: []
EOF
      echo "  Updated: records/work/open.yaml (bootstrap-empty — registries/work/ does not exist yet)"
    fi
  else
    if [[ -d registries/work ]]; then
      echo "  [DRY-RUN] Would sync registries/work/ to records/work/open.yaml"
    else
      echo "  [DRY-RUN] Would write bootstrap-empty records/work/open.yaml (registries/work/ does not exist yet)"
    fi
  fi
}

sync_board() {
  echo "Syncing records/work/open.yaml -> records/board/snapshot.yaml"
  if [[ "$MODE" == "apply" ]]; then
    mkdir -p records/board
    NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    STATUS=$(python3 - "$NOW" <<'PYEOF'
import sys

import yaml

now = sys.argv[1]
work_path = "records/work/open.yaml"
try:
    with open(work_path) as f:
        work = yaml.safe_load(f) or {}
except FileNotFoundError:
    work = {}

items = work.get("items") or []

columns = [
    {"id": "backlog", "name": "Backlog", "items": []},
    {"id": "ready", "name": "Ready", "items": []},
    {"id": "in-progress", "name": "In Progress", "items": []},
    {"id": "done", "name": "Done", "items": []},
]
by_id = {c["id"]: c for c in columns}

for item in items:
    col_id = item.get("column") or "backlog"
    target = by_id.get(col_id, by_id["backlog"])
    target["items"].append(item.get("id"))

# Only ever claim "synced" when real work-item data actually backed the
# columns; otherwise this is still the bootstrap-empty state.
status = "synced" if items else "bootstrap-empty"

doc = {
    "_meta": {
        "generated": now,
        "schema": "urn:multiproduct:schemas:board:snapshot:v1",
        "status": status,
    },
    "columns": columns,
}

header = (
    "# Board snapshot — generated by sync-records.sh at {}\n"
    "# Source: {} ({} open work item(s)); status reflects whether real "
    "work-item data was found there.\n"
).format(now, work_path, len(items))

with open("records/board/snapshot.yaml", "w") as f:
    f.write(header)
    yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False)

print(status)
PYEOF
)
    echo "  Updated: records/board/snapshot.yaml (status=$STATUS)"
  else
    echo "  [DRY-RUN] Would derive records/board/snapshot.yaml columns from records/work/open.yaml (status=synced if real items exist there, else bootstrap-empty)"
  fi
}

case "$SOURCE" in
  people) sync_people;;
  board) sync_board;;
  work) sync_work;;
  all) sync_people; sync_work; sync_board;;
  *) echo "Unknown source: $SOURCE"; exit 2;;
esac

echo ""
echo "Done: L3 sync (mode=$MODE)"
