#!/usr/bin/env bash
# register-schema.sh — L1-02 schema registration (FD-096)
# Usage: bash scripts/l1/register-schema.sh --name <name> --namespace <ns> [--mode dry|apply]
# Creates a new schema file in schemas/<namespace>/<name>.v1.schema.json
set -euo pipefail

NAME=""
NAMESPACE="registry"
MODE="dry"
SCHEMA_URN_PREFIX="urn:multiproduct:schemas"

source contracts/project-config.sh 2>/dev/null || true

while [[ $# -gt 0 ]]; do
  case $1 in
    --name) NAME="$2"; shift 2;;
    --namespace) NAMESPACE="$2"; shift 2;;
    --mode) MODE="$2"; shift 2;;
    *) shift;;
  esac
done

[[ -z "$NAME" ]] && { echo "Usage: $0 --name <name> [--namespace <ns>] [--mode dry|apply]"; exit 2; }

SCHEMA_FILE="schemas/$NAMESPACE/${NAME}.v1.schema.json"
SCHEMA_ID="${SCHEMA_URN:-$SCHEMA_URN_PREFIX}:${NAMESPACE}:${NAME}:v1"

echo "=== Register Schema: $SCHEMA_ID ==="

if [[ "$MODE" == "apply" ]]; then
  mkdir -p "schemas/$NAMESPACE"
  cat > "$SCHEMA_FILE" <<EOF
{
  "\$schema": "http://json-schema.org/draft-07/schema#",
  "\$id": "$SCHEMA_ID",
  "title": "$(echo "$NAME" | sed 's/-/ /g' | sed 's/\b\w/\U&/g')",
  "description": "Schema for $NAME (auto-generated by L1-02, FD-096)",
  "type": "object",
  "required": ["id"],
  "properties": {
    "id": { "type": "string" }
  }
}
EOF
  echo "Created: $SCHEMA_FILE"
  echo "Schema ID: $SCHEMA_ID"
else
  echo "[DRY-RUN] Would create: $SCHEMA_FILE"
  echo "[DRY-RUN] Schema ID: $SCHEMA_ID"
fi
