#!/usr/bin/env bash
# setup-repo-skeleton.sh — L1-01 repo skeleton setup (FD-095)
# Usage: bash scripts/l1/setup-repo-skeleton.sh [--root <path>] [--mode dry|apply]
# Creates the standard directory structure for a new product repo
set -euo pipefail

ROOT="${ROOT:-.}"
MODE="dry"

while [[ $# -gt 0 ]]; do
  case $1 in
    --root) ROOT="$2"; shift 2;;
    --mode) MODE="$2"; shift 2;;
    *) shift;;
  esac
done

make_dir() {
  local DIR="$1"
  if [[ "$MODE" == "apply" ]]; then
    mkdir -p "$ROOT/$DIR"
    touch "$ROOT/$DIR/.gitkeep"
    echo "Created: $DIR"
  else
    echo "[DRY-RUN] Would create: $DIR"
  fi
}

make_file() {
  local FILE="$1"; local CONTENT="$2"
  if [[ "$MODE" == "apply" ]]; then
    mkdir -p "$(dirname "$ROOT/$FILE")"
    echo "$CONTENT" > "$ROOT/$FILE"
    echo "Created: $FILE"
  else
    echo "[DRY-RUN] Would create: $FILE"
  fi
}

echo "=== L1-01 Repo Skeleton Setup (mode=$MODE) ==="
echo "Root: $ROOT"
echo ""

# Standard directories
make_dir "schemas/registry"
make_dir "schemas/product"
make_dir "registries/people"
make_dir "registries/capabilities"
make_dir "registries/roles"
make_dir "registries/platform"
make_dir "registries/policies"
make_dir "registries/exceptions"
make_dir "records/board"
make_dir "records/work"
make_dir "records/commitments"
make_dir "records/products"
make_dir "records/people"
make_dir "records/metrics"
make_dir "records/exceptions"
make_dir "records/audit"
make_dir "validators/registry/rules"
make_dir "scripts/l0"
make_dir "scripts/l1"
make_dir "scripts/metrics"
make_dir "scripts/provision"
make_dir "scripts/git-hooks"
make_dir "tests/integration"
make_dir "docs/assets"
make_dir ".github/workflows"

# Standard files
make_file ".gitignore" "# Generated by L1-01 setup (FD-095)
__pycache__/
*.py[cod]
*.egg-info/
.env
*.log
node_modules/
.DS_Store
Thumbs.db"

make_file "CODEOWNERS" "# CODEOWNERS — all lanes owned by L0 integrator in bootstrap mode (FD-109)
* @bendrohit-eng"

echo ""
echo "Done: repo skeleton (mode=$MODE)"
echo "Next: run L1-02 schema setup, L1-03 validator setup"
