#!/usr/bin/env python3
"""Emit one behavioural envelope per fifth-tier credential.

Section 40.1 line 3685; D96 line 10189; Section 53.4 lines 4704-4716.

The run-count ceiling is COMPUTED - twice the scheduled run count - never
chosen. The expected source host and the alert-config owner are read from the
fifth-tier entries written by L5-02-04, which read them from the frozen
contract. This program supplies no value of its own.

Usage:  emit_envelopes.py [<fifth-tier-dir> [<out-dir>]]
Defaults: access/secrets/fifth-tier  and  access/secrets/envelope
"""
import glob
import os
import sys

import yaml

MULTIPLIER = 2   # Section 40.1 line 3685: "twice the scheduled run count"


def main(argv):
    src = argv[1] if len(argv) > 1 else os.path.join(
        "access", "secrets", "fifth-tier")
    out_dir = argv[2] if len(argv) > 2 else os.path.join(
        "access", "secrets", "envelope")
    paths = sorted(glob.glob(os.path.join(src, "*.yaml")))
    if not paths:
        print("RESULT FAIL no-fifth-tier-entries %s" % src)
        return 2
    entries = []
    for path in paths:
        try:
            with open(path, "r", encoding="utf-8") as handle:
                doc = yaml.safe_load(handle) or {}
        except Exception as exc:                                # fail closed
            print("RESULT FAIL entry-unparseable %s (%s)" % (path, exc))
            return 2
        for key in ("credential_id", "host", "envelope_alert_owner",
                    "scheduled_runs_per_day"):
            if not doc.get(key) and doc.get(key) != 0:
                print("RESULT FAIL entry-missing %s:%s" % (path, key))
                return 2
        runs = int(doc["scheduled_runs_per_day"])
        if runs < 1:
            print("RESULT FAIL non-positive-schedule %s" % path)
            return 2
        entries.append(doc)

    os.makedirs(out_dir, exist_ok=True)
    for doc in entries:
        cred = doc["credential_id"]
        runs = int(doc["scheduled_runs_per_day"])
        ceiling = MULTIPLIER * runs
        lines = []
        lines.append("# %s/%s.envelope.yaml" % (out_dir, cred))
        lines.append("# Generated by access/secrets/tools/emit_envelopes.py.")
        lines.append("# Do not hand-edit: re-run the emitter.")
        lines.append("# Section 40.1 line 3685; D96 line 10189; Section 53.4.")
        lines.append("schema_version: 1")
        lines.append("credential_id: %s" % cred)
        lines.append("spec_anchor: \"Section 40.1\"")
        lines.append("spec_lines: \"3685\"")
        lines.append("decision: D96")
        lines.append("temporal_window_rule: retired")
        lines.append('temporal_window_rule_reason: "Use outside its scheduled window is near-vacuous for a credential that legitimately fires hourly, nightly and on every registry merge, and is silent entirely for read-side abuse (D96)"')
        lines.append("signed_run_record:")
        lines.append("  required: true")
        lines.append("  must_name: scheduled_trigger")
        lines.append('  schema: "access/secrets/schemas/run-record.schema.json"')
        lines.append("  unmatched_run_class: Blocking")
        lines.append('  rationale: "any run without a matching trigger record raises immediately"')
        lines.append("run_count_ceiling_per_day:")
        lines.append("  scheduled_runs_per_day: %d" % runs)
        lines.append("  multiplier: %d" % MULTIPLIER)
        lines.append("  value: %d" % ceiling)
        lines.append("  computed: true")
        lines.append('  status: "calibrated configuration; initial value twice the scheduled run count"')
        lines.append('  recalibrate_when: "the schedule changes"')
        lines.append("  breach_class: Blocking")
        lines.append("expected_source_host:")
        lines.append('  value: "%s"' % doc["host"])
        lines.append("  breach_class: Blocking")
        lines.append('  rationale: "the credential is expected to be used from the host that holds it (Section 40.3 line 3703), so the envelope is host-aware and not only time-aware"')
        lines.append("published_api_call_counts:")
        lines.append("  required: true")
        lines.append("  per: run")
        lines.append("  absent_class: Blocking")
        lines.append('  rationale: "read-side abuse - enumerating and cloning every private repository - emits no webhook and no event-log entry, so it must surface as a volume anomaly rather than as nothing"')
        lines.append("objects_mutated_cap: not-in-envelope-v1")
        lines.append('objects_mutated_cap_escalation: "E-P2-01 - D96 names per-run caps on objects mutated; the Section 40.1 line 3685 envelope list does not, and the frozen contract carries no key for it. L0 decides."')
        lines.append("outside_envelope_class: Blocking")
        lines.append('severity_scale: "Section 53.4 lines 4704-4716 - the only severity scale in the system"')
        lines.append('alert_config_owner: "%s"' % doc["envelope_alert_owner"])
        lines.append("alert_config_owner_is_named_control: true")
        lines.append('alert_config_owner_rationale: "so the alert on a run outside the envelope is itself an owned control, not an unowned hope (Section 40.1 line 3683)"')
        lines.append('evaluator: "access/secrets/envelope/check-envelope.sh"')
        body = "\n".join(lines) + "\n"
        with open(os.path.join(out_dir, "%s.envelope.yaml" % cred), "w",
                  encoding="utf-8", newline="\n") as handle:
            handle.write(body)
        print("WROTE %s/%s.envelope.yaml ceiling=%d" % (out_dir, cred, ceiling))
    print("RESULT PASS %d" % len(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
