#!/usr/bin/env python3
"""Emit infra/network/ops-vm-shell-gate.yaml from the frozen contract.

Section 40.3 line 3703, enforcement E2 of boundary 2: "shell access to the
operations VM requires a second factor on top of the private network path of
Section 51.4."

"On top of" is load-bearing. The private network path is not the second factor;
it is the path the second factor sits on. Both are required, separately.

Key ids and the hostname come from contracts/access/access-inputs.yaml. This
program names no host and no key of its own.

Usage: emit_shell_gate.py [<inputs.yaml> [<out-path>]]
"""
import os
import sys

import yaml

ALLOWED_KEY_TYPES = [
    "sk-ssh-ed25519@openssh.com",
    "sk-ecdsa-sha2-nistp256@openssh.com",
]


def main(argv):
    inputs = argv[1] if len(argv) > 1 else os.path.join(
        "contracts", "access", "access-inputs.yaml")
    out = argv[2] if len(argv) > 2 else os.path.join(
        "infra", "network", "ops-vm-shell-gate.yaml")
    if not os.path.isfile(inputs):
        print("RESULT FAIL inputs-unreadable %s" % inputs)
        return 2
    try:
        with open(inputs, "r", encoding="utf-8") as handle:
            doc = yaml.safe_load(handle) or {}
    except Exception as exc:                                    # fail closed
        print("RESULT FAIL inputs-unparseable %s" % exc)
        return 2
    block = doc.get("ops_vm")
    if not isinstance(block, dict):
        print("RESULT FAIL no-ops_vm-block %s" % inputs)
        return 2
    hostname = str(block.get("hostname") or "").strip()
    keys = block.get("shell_second_factor_key_ids") or []
    if not hostname:
        print("RESULT FAIL ops_vm.hostname-empty")
        return 2
    if not keys:
        print("RESULT FAIL ops_vm.shell_second_factor_key_ids-empty")
        return 2

    lines = []
    lines.append("# infra/network/ops-vm-shell-gate.yaml")
    lines.append("# Generated by access/secrets/tools/emit_shell_gate.py. Do not hand-edit.")
    lines.append("# Section 40.3 line 3703 (boundary 2, enforcement E2);")
    lines.append("# Section 51.4 lines 4487-4498 (the private network path it sits on top of).")
    lines.append("schema_version: 1")
    lines.append("boundary: boundary-2-control-plane")
    lines.append("enforcement_id: E2")
    lines.append("decision: D95")
    lines.append('host: "%s"' % hostname)
    lines.append("private_network_path_required: true")
    lines.append('private_network_path_source: "Section 51.4 - every control-plane surface is reachable only over a private network path with SSO in front of it"')
    lines.append("private_network_path_is_the_second_factor: false")
    lines.append('private_network_path_note: "Section 40.3 says the second factor is ON TOP OF the private path. Treating the path as the factor leaves one factor."')
    lines.append("second_factor:")
    lines.append("  mechanism: hardware-backed-ssh-key")
    lines.append("  key_types_allowed:")
    for key_type in ALLOWED_KEY_TYPES:
        lines.append('    - "%s"' % key_type)
    lines.append("  touch_required: true")
    lines.append("  no_touch_required_permitted: false")
    lines.append("  authorized_key_ids:")
    for key in keys:
        lines.append('    - "%s"' % key)
    lines.append("sshd_required_settings:")
    lines.append('  PasswordAuthentication: "no"')
    lines.append('  KbdInteractiveAuthentication: "no"')
    lines.append('  PermitRootLogin: "no"')
    lines.append('  AuthenticationMethods: "publickey"')
    lines.append('  PubkeyAuthentication: "yes"')
    lines.append('verifier: "infra/network/check-shell-gate.sh"')
    lines.append('spec_anchor: "Section 40.3"')
    lines.append('spec_lines: "3703"')
    body = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(body)
    print("WROTE %s keys=%d" % (out, len(keys)))
    print("RESULT PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
