#!/usr/bin/env python3
"""Emit the five fifth-tier credential entries from the frozen contract.

Section 40.1 line 3683 ("Fifth-tier operations"); Section 49.1 lines 4338-4342;
Section 14.4 lines 1256-1267 (the escrow is the re-issue source); Section 51.5
line 4502 (why this tier lives on the operations VM).

This program CHOOSES NOTHING. Every person id, host and permission string is
read from contracts/access/access-inputs.yaml. If any of the five credentials
is missing any required contract value, nothing is written at all: a partially
populated fifth tier reads as complete and is worse than none.

Usage:  emit_fifth_tier.py [<inputs.yaml> [<out-dir>]]
Defaults: contracts/access/access-inputs.yaml  and  access/secrets/fifth-tier
"""
import os
import sys

import yaml

ORDER = [
    "reconciler",
    "provisioning-cli",
    "organisation-export-token",
    "records-writer",
    "layer-b-backup",
]
REQUIRED = [
    "rotator",
    "envelope_alert_owner",
    "expected_source_host",
    "scheduled_runs_per_day",
    "permission_set",
]
SPEC_KIND = "least-privilege GitHub App or fine-grained PAT"
KIND = {
    "reconciler": (SPEC_KIND, False),
    "provisioning-cli": (SPEC_KIND, False),
    "organisation-export-token": (SPEC_KIND, False),
    "records-writer": (
        "GitHub App installation token whose fine-grained contents: write is scoped to the records repository alone",
        True),
    "layer-b-backup": ("append-only object-store credential", True),
}
NOTES = {
    "reconciler": [
        "Section 99.6 risk 6: the reconciler is the highest-privilege identity in the system.",
        "Its declared bounds are executed by AT-110, not asserted, and re-executed at every rotation.",
        "Section 26.4: the declared repair scope is the only machine write path on the control-plane repository.",
        "D89: no bypass actor exists on the control-plane repository.",
        "It additionally holds check-run write on product repositories for exactly one named check; a check run carries status only, writes no repository content, approves nothing, and satisfies no gate a human is required to satisfy (Section 40.1).",
    ],
    "provisioning-cli": [
        "Provisioning applies declared access state; it never authors it.",
    ],
    "organisation-export-token": [
        "Section 45.3: the organisation export is the off-site anchor; its target is object-locked.",
        "Section 40.3: this token plus the reconciler credential are why the second trust boundary exists.",
    ],
    "records-writer": [
        "D89: the record stores live in their own repository; this credential holds nothing on the control-plane repository at all.",
        "D107: append-only is enforced by a no-bypass ruleset, signed commits and a per-run SHA anchor - not by review.",
    ],
    "layer-b-backup": [
        "Section 51.4: append-only and write-only, to object-locked versioned storage in a different provider and credential domain than the operations VM.",
        "The party who can write the backup can neither read it nor destroy backup history.",
        "Custody of the backup encryption key is the Section 14.4 escrow.",
    ],
}


def fail(message):
    print("RESULT FAIL %s" % message)
    return 2


def main(argv):
    inputs = argv[1] if len(argv) > 1 else os.path.join(
        "contracts", "access", "access-inputs.yaml")
    out_dir = argv[2] if len(argv) > 2 else os.path.join(
        "access", "secrets", "fifth-tier")
    if not os.path.isfile(inputs):
        return fail("inputs-unreadable %s" % inputs)
    try:
        with open(inputs, "r", encoding="utf-8") as handle:
            doc = yaml.safe_load(handle) or {}
    except Exception as exc:                                    # fail closed
        return fail("inputs-unparseable %s" % exc)
    block = doc.get("fifth_tier")
    if not isinstance(block, dict):
        return fail("no-fifth_tier-block %s" % inputs)
    missing = []
    for cred in ORDER:
        entry = block.get(cred)
        if not isinstance(entry, dict):
            missing.append("%s: absent" % cred)
            continue
        for key in REQUIRED:
            value = entry.get(key)
            if value is None or value == "" or value == []:
                missing.append("%s: %s" % (cred, key))
    if missing:
        for line in missing:
            print("MISSING %s" % line)
        return fail("%d-missing-contract-values" % len(missing))

    os.makedirs(out_dir, exist_ok=True)
    for cred in ORDER:
        entry = block[cred]
        kind, narrowed = KIND[cred]
        lines = []
        lines.append("# %s/%s.yaml" % (out_dir, cred))
        lines.append("# Generated by access/secrets/tools/emit_fifth_tier.py from")
        lines.append("# contracts/access/access-inputs.yaml. Do not hand-edit: re-run the emitter.")
        lines.append("# Section 40.1 line 3683; Section 49.1 lines 4338-4342.")
        lines.append("schema_version: 1")
        lines.append("credential_id: %s" % cred)
        lines.append("tier_id: control_plane")
        lines.append("rank: 5")
        lines.append('location: "Machine-credential store on the hosts that use them"')
        lines.append('kind: "%s"' % kind)
        lines.append("kind_narrowed: %s" % ("true" if narrowed else "false"))
        if not narrowed:
            lines.append('kind_narrowing_authority: "L0 - Section 40.1 permits either; narrowing is a recorded decision, never an executor choice"')
        lines.append('host: "%s"' % entry["expected_source_host"])
        lines.append("rotation_cadence: quarterly")
        lines.append('rotation_cadence_status: "calibrated configuration; initial value quarterly (Section 40.1 line 3683)"')
        lines.append('rotator: "%s"' % entry["rotator"])
        lines.append("rotator_capability_required: devops")
        lines.append('runbook: "access/secrets/runbooks/rotate-fifth-tier-credential.md"')
        lines.append('envelope: "access/secrets/envelope/%s.envelope.yaml"' % cred)
        lines.append('envelope_alert_owner: "%s"' % entry["envelope_alert_owner"])
        lines.append("scheduled_runs_per_day: %d" % int(entry["scheduled_runs_per_day"]))
        lines.append("permission_set:")
        for permission in entry["permission_set"]:
            lines.append('  - "%s"' % permission)
        lines.append('permission_set_published_at: "access/published/secret-tiers.v1.json"')
        lines.append('reissue_source: "Section 14.4 escrow"')
        lines.append("compromise_class: security-incident")
        lines.append('compromise_authority: "Section 43 (Security Incident Workflow)"')
        lines.append('inventory_entry_owner: "L5-05-02 -> assets/inventory/machine-credential-%s.yaml"' % cred)
        lines.append('spec_anchor: "Section 40.1"')
        lines.append('spec_lines: "3683"')
        lines.append("notes:")
        for note in NOTES[cred]:
            lines.append('  - "%s"' % note)
        body = "\n".join(lines) + "\n"
        with open(os.path.join(out_dir, "%s.yaml" % cred), "w",
                  encoding="utf-8", newline="\n") as handle:
            handle.write(body)
        print("WROTE %s/%s.yaml" % (out_dir, cred))
    print("RESULT PASS %d" % len(ORDER))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
