#!/usr/bin/env bash
# Resolves each third-party action's latest release tag to a full commit SHA
# and writes .github/workflows/_pins/pins.env. Spec Section 33.2, Section 48.1.
# Deterministic given the upstream repository state; no choice is made here.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
OUT=.github/workflows/_pins/pins.env
ACTIONS="ACTIONS_CHECKOUT:actions/checkout
ACTIONS_SETUP_PYTHON:actions/setup-python
ACTIONS_UPLOAD_ARTIFACT:actions/upload-artifact
ACTIONS_DOWNLOAD_ARTIFACT:actions/download-artifact
ACTIONS_GITHUB_SCRIPT:actions/github-script
DOCKER_SETUP_BUILDX:docker/setup-buildx-action
DOCKER_LOGIN:docker/login-action
DOCKER_BUILD_PUSH:docker/build-push-action"
: > "$OUT"
echo "# GENERATED by resolve-pins.sh — do not hand-edit. Spec 33.2, 48.1." >> "$OUT"
echo "# Regenerate with: bash .github/workflows/_pins/resolve-pins.sh" >> "$OUT"
while IFS=: read -r key repo; do
  [ -z "$key" ] && continue
  tag="$(gh api "repos/${repo}/releases/latest" --jq '.tag_name')"
  sha="$(gh api "repos/${repo}/commits/${tag}" --jq '.sha')"
  case "$sha" in
    [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]) : ;;
    *) echo "FATAL: ${repo}@${tag} did not resolve to a 40-hex SHA" >&2; exit 1 ;;
  esac
  echo "PIN_${key}_REPO=${repo}"  >> "$OUT"
  echo "PIN_${key}_SHA=${sha}"    >> "$OUT"
  echo "PIN_${key}_TAG=${tag}"    >> "$OUT"
done <<< "$ACTIONS"
echo "wrote $OUT"
