#!/usr/bin/env bash
# Lane 2 Phase 3 precondition gate.
# Spec: MultiProduct_MasterSpec_v4.0.md Sections 27.2 (2567-2576), 37.3 (3261-3268),
#       39.5 (3589-3596), 33.4 (2911). Decisions D52, D73, D87, D91.
# Resolves the consumed contract surface. Fails closed: any missing key aborts.
# Re-runnable. Writes tools/evidence/phase3-contract.env.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

if [ ! -d contracts ]; then
  echo "PHASE3_CONTRACTS_ABSENT"
  exit 1
fi

KEYS="control_plane_slug records_repo_slug records_writer_secret_name \
registry_read_secret_name workflows_tag production_approval_record_glob \
verification_block_store exceptional_authorisation_store \
privileged_runner_marker_path ephemeral_runner_marker_path \
rollback_workflow_filename"

OUT="tools/evidence/phase3-contract.env"
TMP="$(mktemp)"
echo "# GENERATED by tools/evidence/phase3-preconditions.sh — do not hand-edit." > "$TMP"
echo "# Resolved from contracts/** at commit $(git rev-parse HEAD)" >> "$TMP"

MISSING=""
for k in $KEYS; do
  # A contract key is a top-level or nested YAML scalar. Take the first
  # occurrence in lexical file order; contracts/** is frozen, so it is stable.
  v="$(grep -rhE "^[[:space:]]*${k}:[[:space:]]*[^[:space:]#]" contracts/ 2>/dev/null \
        | head -n 1 \
        | sed -E "s/^[[:space:]]*${k}:[[:space:]]*//" \
        | sed -E 's/[[:space:]]*#.*$//' \
        | tr -d '"'"'"'' )"
  if [ -z "${v}" ]; then
    MISSING="${MISSING} ${k}"
    continue
  fi
  printf '%s=%s\n' "$(echo "$k" | tr '[:lower:]' '[:upper:]')" "${v}" >> "$TMP"
done

if [ -n "${MISSING}" ]; then
  echo "PHASE3_CONTRACT_KEY_MISSING:${MISSING}"
  rm -f "$TMP"
  exit 1
fi

mv "$TMP" "$OUT"
echo "PHASE3_PRECONDITIONS_OK"
