#!/usr/bin/env bash
# make-fixture.sh — generates a passing baseline registry fixture (FD-094, Option B)
# Usage: bash make-fixture.sh > fixture-passing.yaml
set -euo pipefail
cat <<'EOF'
# Baseline registry fixture — generated by make-fixture.sh
# Must pass all L1 validator rules R01-R18
people: []
capabilities: []
roles: []
EOF
