#!/usr/bin/env python3
"""Rotator / host-root separation, or the recorded accepted risk.

Section 40.3 line 3703; Section 90.3 line 7982 (the accepted-risk shape);
Section 54.2 lines 4787-4797 (expiry and compensating control are mandatory).

Three states and no fourth:
  separated     no fifth-tier rotator is the host-root holder            exit 0
  accepted-risk at least one is, and a COMPLETE record exists            exit 0
  UNRESOLVED    at least one is, and no complete record exists           exit 1

An UNRESOLVED result is exactly what Section 40.3 calls "an unstated default",
which it forbids. It is a decision for L0, never for the executor.

Usage:
  check_separation.py [<inputs.yaml> [<accepted-risk.yaml>]] [--write]

--write emits access/secrets/separation/separation.result.yaml.
Exit 0 resolved, 1 unresolved or incomplete record, 2 input fault.
"""
import os
import sys

import yaml

REQUIRED_RECORD_FIELDS = [
    "risk_id",
    "statement",
    "holder",
    "does_not_confer",
    "compensating_control",
    "compensating_control_store",
    "compensating_control_cadence",
    "review_date",
    "review_cadence",
    "expiry",
    "deactivation_trigger",
    "owner",
    "accepted_by",
    "accepted_at",
]
RESULT_PATH = os.path.join("access", "secrets", "separation",
                           "separation.result.yaml")


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    write = "--write" in argv
    inputs = args[0] if args else os.path.join(
        "contracts", "access", "access-inputs.yaml")
    record_path = args[1] if len(args) > 1 else os.path.join(
        "contracts", "access", "accepted-risks", "rotator-hostroot.yaml")
    if not os.path.isfile(inputs):
        print("RESULT FAIL inputs-unreadable %s" % inputs)
        return 2
    try:
        with open(inputs, "r", encoding="utf-8") as handle:
            doc = yaml.safe_load(handle) or {}
    except Exception as exc:                                    # fail closed
        print("RESULT FAIL inputs-unparseable %s" % exc)
        return 2
    fifth = doc.get("fifth_tier")
    ops = doc.get("ops_vm")
    if not isinstance(fifth, dict) or not isinstance(ops, dict):
        print("RESULT FAIL contract-shape fifth_tier/ops_vm")
        return 2
    root_holder = str(ops.get("host_root_holder") or "").strip()
    if not root_holder:
        print("RESULT FAIL ops_vm.host_root_holder-empty")
        return 2

    collisions = []
    for cred in sorted(fifth):
        entry = fifth.get(cred) or {}
        rotator = str(entry.get("rotator") or "").strip()
        if not rotator:
            print("RESULT FAIL rotator-empty %s" % cred)
            return 2
        if rotator == root_holder:
            collisions.append(cred)
            print("CONCENTRATION %s rotator=%s is also host_root_holder" % (cred, rotator))

    state = None
    holder = ""
    review = ""
    if not collisions:
        state = "separated"
        print("SEPARATION separated")
    else:
        if not os.path.isfile(record_path):
            print("SEPARATION UNRESOLVED no accepted-risk record at %s" % record_path)
            print("QUOTE Section 40.3: never an unstated default")
            print("RESULT FAIL")
            return 1
        try:
            with open(record_path, "r", encoding="utf-8") as handle:
                rec = yaml.safe_load(handle) or {}
        except Exception as exc:                                # fail closed
            print("RESULT FAIL record-unparseable %s" % exc)
            return 2
        missing = [f for f in REQUIRED_RECORD_FIELDS
                   if not str(rec.get(f) or "").strip()]
        if missing:
            for field in missing:
                print("RECORD-INCOMPLETE %s" % field)
            print("QUOTE Section 54.2: An accepted risk with no named holder, no compensating control and no expiry is undocumented policy")
            print("SEPARATION accepted-risk-incomplete")
            print("RESULT FAIL")
            return 1
        state = "accepted-risk"
        holder = str(rec["holder"])
        review = str(rec["review_date"])
        print("SEPARATION accepted-risk holder=%s review=%s" % (holder, review))

    if write:
        lines = []
        lines.append("# %s" % RESULT_PATH)
        lines.append("# Generated by access/secrets/separation/check_separation.py.")
        lines.append("# Section 40.3 line 3703. Do not hand-edit: re-run the checker.")
        lines.append("schema_version: 1")
        lines.append("boundary: boundary-2-control-plane")
        lines.append("enforcement_id: E3")
        lines.append("state: %s" % state)
        if collisions:
            lines.append("concentrated_credentials:")
            for cred in collisions:
                lines.append("  - %s" % cred)
        else:
            lines.append("concentrated_credentials: []")
        lines.append('holder: "%s"' % holder)
        lines.append('review_date: "%s"' % review)
        if state == "accepted-risk":
            lines.append('compensating_control: "see contracts/access/accepted-risks/rotator-hostroot.yaml"')
        else:
            lines.append('compensating_control: ""')
        lines.append('spec_anchor: "Section 40.3"')
        lines.append('spec_lines: "3703"')
        os.makedirs(os.path.dirname(RESULT_PATH), exist_ok=True)
        with open(RESULT_PATH, "w", encoding="utf-8", newline="\n") as handle:
            handle.write("\n".join(lines) + "\n")
        print("WROTE %s" % RESULT_PATH)
    print("RESULT PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
